### ISSUE TITLE
Exception : BadTooManySubscriptions

### ISSUE THREAD

**Issue by zoheirdib** [technosoftware-gmbh/opcua-solution-net#3]
# Introduction:

We are using the OPC-UA V2.1.x
We implement a Server and a client with the same SDK.
 
# Issue description: 

1)Start the server and the client for the first time =>both server and client are started.
2) Connect the client to the server => connection between server and client is successful
3)Client subscribe to N nodes => subscription is successful, client is notified correctly if states of suscribed nodes are modified by the server.
4) Close the client => we close only the client, the server is still running
5) re-start the client => client started
6) Connect the client to the server => connection between server and client is successful
7) Client subscribe to the same N nodes as before (see step 3) => Opc.Ua.ServiceResultException : 'BadTooManySubscriptions

# Help Whanted
Could you please help us to solve this issue ? 

Regards.
Zoheir

**Comment by technosoftware** [comment]
Dear Zoheir

In the configuration file for the server you have the option:

`<MaxSubscriptionCount>100</MaxSubscriptionCount>`

This specifies the maximum number of subscriptions the server can handle. That is the total number counted over all clients.

If a client application closes without closing subscriptions and sessions correctly there is another parameter specifying that behavior:

`<MaxSubscriptionLifetime>3600000</MaxSubscriptionLifetime>`

This controls the maximum time how long the subscriptions will remain open without a publish from the client (in ms).

Maybe you have to adapt these parameters for your needs and in case 4) is for a normal application exit you should check if your client closes all used subscriptions and sessions.

Best regards
Thomas

**Comment by technosoftware** [comment]
Closing this issue. No feedback so we assume question was helping.

**Comment by zoheirdib** [comment]
Dear Thomas,

Thank you for your replay. 

Using the Following parameter fixed our issue about the exception in the point of view of the server.
 <MaxSubscriptionCount>10000</MaxSubscriptionCount> and <MaxSubscriptionLifetime>100</MaxSubscriptionLifetime>

To fix the issue on the side of the client, i guess we need to close the session and subscription before closing the client app. Could you please show us how we should do that ?

I try this instructions but it don't seem to work :

1- Create and add suscription
 mySuscription = new Subscription(m_opcClient.Session.DefaultSubscription) { PublishingInterval = 1000 };
 mySession .AddSubscription(mySuscription );
 mySuscription .Create();

2- Remove the suscription before closing the client app
mySuscription .RemoveSubscription(mySuscription );

3- Closing the session before closing the client app
mySession .close();

Could you help us please ? 

Thank you in advance.
Zoheir.

**Comment by technosoftware** [comment]
Dear Zoheir

With step 3 you are removing the subscription from the session, but you don't close it. If you are doing that you have afterwards to call

mySubscription.Dispose();

Or you remove that and just use the following:

3- Closing the session before closing the client app

`mySession.Close();`
`mySession.Dispose();`

The mySession.Dispose() will remove and close all subscriptions added to the session. And the Dispose() you need anyway.

And after you have done this I assume you even don't need increasing 

`<MaxSubscriptionCount>100</MaxSubscriptionCount>`

Best regards
Thomas
